#pragma once

#include <memory>
#include <string>

#include <grpcpp/grpcpp.h>

#include "absl/strings/string_view.h"
#include "absl/types/span.h"

#include "main/inc/transport.h"            // adjust if transport.h lives elsewhere
#include "main/proto/unary_sim.grpc.pb.h"  // generated by :unary_sim_cc_grpc

class GrpcTransport final : public Transport
{
public:
    explicit GrpcTransport(const std::string &target);

    void Execute(absl::string_view module, absl::Span<const TensorView> inputs,
                 DoneCallback done) override;

private:
    std::unique_ptr<simulator::Simulator::Stub> stub_;
};